// Copyright (c) 2022 TikTok Pte. Ltd.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.
package com.tiktok.sparkling.method.storage.getItem

import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodName
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamField
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodResultModel
import com.tiktok.sparkling.method.registry.core.base.AbsSparklingIDLMethod
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseParamModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseResultModel


/** anycode-lint-ignore */

/**
 * GENERATED BY ANYCODE.
 * DO NOT MODIFY!!!
 */
abstract class AbsStorageGetItemMethodIDL : AbsSparklingIDLMethod<AbsStorageGetItemMethodIDL.IDLMethodGetStorageItemParamModel, AbsStorageGetItemMethodIDL.IDLMethodGetStorageItemResultModel>() {

    @IDLMethodName(name = "storage.getItem", params = ["key", "biz"], results = ["data"])
    final override val name: String = "storage.getItem"

    @IDLMethodParamModel
    interface IDLMethodGetStorageItemParamModel : IDLMethodBaseParamModel {

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "key")
        val key: String

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "biz")
        val biz: String?
    }

    @IDLMethodResultModel
    interface IDLMethodGetStorageItemResultModel: IDLMethodBaseResultModel {

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "data")
        @set:IDLMethodParamField(required = false, isGetter = false, keyPath = "data")
        var data: Any?
    }
}