// Generated by sparkling autolink
import Foundation

struct SparklingAutolinkModule {
    let name: String
    let iosModuleName: String?
    let className: String?
}

let sparklingAutolinkBundleId = "com.example.sparkling.go"
let sparklingAutolinkModules: [SparklingAutolinkModule] = [
    SparklingAutolinkModule(name: "sparkling-router", iosModuleName: "SPKRouter", className: "RouterMethod")
]
