platform :ios, '12.0'

# Use private spec repo for SparklingMethod and Sparkling
source 'https://cdn.cocoapods.org/'

use_modular_headers!

install! 'cocoapods',
:generate_multiple_pod_projects => true,
:incremental_installation => true,
:deterministic_uuids => true

inhibit_all_warnings!

def sparkling_methods
  pod 'SparklingMethod', :path => '../../../packages/sparkling-method-sdk/ios', :subspecs => [
  'Lynx', 'DIProvider', 'Debug'
  ]
end

def sparkling_methods_dep
  # BEGIN SPARKLING AUTOLINK
  pod 'Sparkling-SPKRouter', :path => '../node_modules/sparkling-router/ios'
  pod 'Sparkling-SPKStorage', :path => '../../../packages/methods/sparkling-storage/ios'
  # END SPARKLING AUTOLINK
end

def sparkling_kit
  pod 'Sparkling', :path => '../../../packages/sparkling-sdk/ios'
  sparkling_methods
  sparkling_methods_dep
  
  pod 'Lynx', '3.5.1', :subspecs => [
    'Framework',
    'ReleaseResource'
  ]
  
  pod 'PrimJS', '2.15.0-rc.2', :subspecs => ['quickjs', 'napi']

  pod 'LynxService', '3.5.1', :subspecs => [
  'Image',
  'Log',
  'Http',
  'Devtool'
  ]

#  pod 'BaseDevtool'
  pod 'LynxDevtool', '3.5.1', :subspecs => [
   'Framework',
  ]
  
  pod 'SnapKit'
  pod 'Mantle', '~> 2.2.0'
  
  pod 'SDWebImage','5.15.5'
  pod 'SDWebImageWebPCoder', '0.11.0'
  
end

use_frameworks!
target 'SparklingGo' do
  sparkling_kit
end

target 'SparklingGoTests' do
  sparkling_kit
end

target 'SparklingMethodTests' do
  sparkling_kit
end

target 'SparklingGoUITests' do
  sparkling_kit
end
