// Copyright (c) 2023 TikTok Pte. Ltd.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.

/** anycode-lint-ignore */
package com.tiktok.sparkling.method.router.open

import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodName
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamField
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodResultModel
import com.tiktok.sparkling.method.registry.core.base.AbsSparklingIDLMethod
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseParamModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseResultModel

/** anycode-lint-ignore */

/**
 * GENERATED BY ANYCODE.
 * DO NOT MODIFY!!!
 */
abstract class AbsRouterOpenMethodIDL : AbsSparklingIDLMethod<AbsRouterOpenMethodIDL.IDLMethodOpenParamModel, AbsRouterOpenMethodIDL.IDLMethodOpenResultModel>() {

    @IDLMethodName(name = "router.open", params = ["scheme", "replace", "replaceType", "useSysBrowser", "animated", "interceptor", "extra", "usePost", "postBody", "postHeader"])
    final override val name: String = "router.open"


    @IDLMethodParamModel
    interface IDLMethodOpenParamModel : IDLMethodBaseParamModel {

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "scheme")
        val scheme: String

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "replace")
        val replace: Boolean?

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "replaceType")
        val replaceType: String?

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "useSysBrowser")
        val useSysBrowser: Boolean?

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "animated")
        val animated: Boolean?

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "interceptor")
        val interceptor: String?

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "extra", nestedClassType = IDLMethodOpenExtra::class)
        val extra: IDLMethodOpenExtra?

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "usePost")
        val usePost: Boolean?

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "postBody")
        val postBody: String?

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "postHeader")
        val postHeader: Any?
    }

    @IDLMethodResultModel
    interface IDLMethodOpenResultModel: IDLMethodBaseResultModel {
    }

    interface IDLMethodOpenExtra : IDLMethodBaseModel {
    }
}