// Copyright (c) 2025 TikTok Pte. Ltd.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.
import type { AndroidDsl } from "./types";

export function androidManifestTemplate(packageName: string): string {
  return [
    '<?xml version="1.0" encoding="utf-8"?>',
    `<manifest package="${packageName}">`,
    '    <!-- Library manifest placeholder. Add <application> or <uses-permission> entries as needed. -->',
    '</manifest>',
    '',
  ].join('\n');
}

export function androidGradleTemplate(
  namespace: string,
  dsl: AndroidDsl
): string {
  return dsl === "kts" ? kotlinGradle(namespace) : groovyGradle(namespace);
}

function groovyGradle(namespace: string): string {
  return [
    'plugins {',
    "    id 'com.android.library'",
    "    id 'org.jetbrains.kotlin.android'",
    '}',
    '',
    'android {',
    `    namespace '${namespace}'`,
    '    compileSdk 34',
    '',
    '    defaultConfig {',
    '        minSdk 23',
    '    }',
    '}',
    '',
    '// Add dependencies required by your module.',
    '',
  ].join('\n');
}

function kotlinGradle(namespace: string): string {
  return [
    'plugins {',
    '    id("com.android.library")',
    '    id("org.jetbrains.kotlin.android")',
    '}',
    '',
    'android {',
    `    namespace = "${namespace}"`,
    '    compileSdk = 34',
    '',
    '    defaultConfig {',
    '        minSdk = 23',
    '    }',
    '}',
    '',
    '// Add dependencies required by your module.',
    '',
  ].join('\n');
}

export function iosPodspecTemplate(moduleId: string): string {
  return [
    'Pod::Spec.new do |s|',
    `  s.name             = 'Sparkling-${moduleId}'`,
    "  s.version          = '0.1.0'",
    `  s.summary          = '${moduleId} sparkling method module'`,
    "  s.description      = 'Generated by sparkling-method init. Fill in details before publishing.'",
    `  s.homepage         = 'https://example.com/${moduleId}'`,
    "  s.license          = { :type => 'Apache-2.0' }",
    "  s.author           = { 'sparkling' => 'dev@example.com' }",
    "  s.source           = { :path => '.' }",
    "  s.source_files     = 'Source/**/*.{h,m,mm,swift}'",
    "  s.swift_version    = '5.0'",
    'end',
    '',
  ].join('\n');
}
